### ISSUE TITLE
Duplicate suggestions for already imported "unimported" completions

### ISSUE THREAD

**Issue by MatthewMckee4** [astral-sh/ty#1724]
### Summary

I guess we do no filtering to remove duplicates.

<img width="480" height="238" alt="Image" src="https://github.com/user-attachments/assets/6b685833-4674-41be-ba64-db3331e11188" />

I would expect not to see `TypeVar (import typing)` here.

**Comment by BurntSushi** [comment]
I think the problem is here:

https://github.com/astral-sh/ruff/blob/05d053376b73b911b74dcbad647d2ae6a988b505/crates/ty_ide/src/completion.rs#L64-L65

Actually, I think there are two problems here.

1. `dedup_by` only deals with adjacent duplicates. That may have been fine at one point, but the ranking has grown more sophisticated and probably isn't appropriate any more.
2. The deduplication is done on the symbol name _and_ module name. A symbol in scope lacks a module name. An auto-import symbol always has a module name. So fundamentally, a symbol in scope will never deduplicate with an auto-import symbol.

Since auto-import symbols always come with a module name, then I think one way to deduplicate them with in scope symbols is to find the module in which each symbol in scope is defined. Then compare it with the module name on the auto-import symbol.

We might be able to add this information here:

https://github.com/astral-sh/ruff/blob/05d053376b73b911b74dcbad647d2ae6a988b505/crates/ty_ide/src/importer.rs#L358-L362

Actually, I think we already have it?

https://github.com/astral-sh/ruff/blob/05d053376b73b911b74dcbad647d2ae6a988b505/crates/ty_python_semantic/src/semantic_model.rs#L335

Since we're already computing the set of members in scope at the cursor in order to figure out how to write import edits.

Then I think we can deduplicate here:

https://github.com/astral-sh/ruff/blob/05d053376b73b911b74dcbad647d2ae6a988b505/crates/ty_ide/src/completion.rs#L539-L566

**Comment by kouhe3** [comment]
fixed in latest version.

<img width="854" height="380" alt="Image" src="https://github.com/user-attachments/assets/277dc1aa-147e-4939-91aa-1f85ee9fecda" />

**Comment by MichaReiser** [comment]
I can still reproduce seeing two `TypeVar` completions in the most recent playground
